services:
	postgres:
		image: postgres:13
		environment:
			POSTGRES_USER: airflow
			POSTGRES_PASSWORD: airflow
			POSTGRES_DB: airflow
		volumes:
			- postgres-db-volume:/var/lib/postgresql/data
		healthcheck:
			test: ["CMD", "pg_isready", "-U", "airflow"]
			interval: 5s
			retries: 5
		restart: always

# Command for Windows
# Drafted from above section
# The windows volume bit is a bit messy, check the timestamp on the video: 5:20
docker run -it \\
	-e POSTGRES_USER="root" \\
	-e POSTGRES_PASSWORD="root" \\
	-e POSTGRES_DB="ny_taxi" \\
	-v c:Users/user/.../ny_taxi_postgres_data:var/lib/postgresql/data \\
	-p 5432:5432
	postgres:13

# Command for Linux
# copied from above section
# Same command but for window
docker run -it \\
	-e POSTGRES_USER="root" \\
	-e POSTGRES_PASSWORD="root" \\
	-e POSTGRES_DB="ny_taxi" \\
	-v $(pwd)/ny_taxi_postgres_data:var/lib/postgresql/data \\
	-p 5432:5432
	postgres:13